meal_plans/urls.py
from django.urls import path
from meal_plans.views import (
     MealPlansListView,
     MealPlansDetailView,
     MealPlansCreateView,
     MealPlansUpdateView,
     MealPlansDeleteView,
)


urlpatterns = [
    path("", MealPlansListView.as_view(), name="meal_plans_list"),
    path("<int:pk>/", MealPlansDetailView.as_view(), name="meal_plans_detail"),
    path("create/", MealPlansCreateView.as_view(), name="meal_plans_create"),
    path("<int:pk>/edit/", MealPlansUpdateView.as_view(), name="meal_plans_edit"),
    path("<int:pk>/delete/", MealPlansDeleteView.as_view(), name="meal_plans_delete"),
]

scrumptious/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path(
        "accounts/login/", auth_views.LoginView.as_view(), name="login"
    ),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("admin/", admin.site.urls),
    path("recipes/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path("meal_plans/", include("meal_plans.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagListView,
    TagDeleteView,
    TagDetailView,
    TagCreateView,
    TagUpdateView,
)

urlpatterns = [
    path("", TagListView.as_view(), name="tags_list"),
    path("<int:pk>/", TagDetailView.as_view(), name="tag_detail"),
    path("<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
    path("new/", TagCreateView.as_view(), name="tag_new"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="tag_edit"),
]

meal_plans/models.py
from django.db import models
from django.conf import settings


# Create your models here.


class MealPlan(models.Model):
    name = models.CharField(max_length=120)
    date = models.DateField()
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name=("meal_plan"),
        on_delete=models.CASCADE,
        null=True,
    )
    recipes = models.ManyToManyField(
        "recipes.Recipe",
        related_name="meal_plans",
    )

    def __str__(self):
        return self.name

meal_plans/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from meal_plans.models import MealPlan


class MealPlansListView(LoginRequiredMixin, ListView):
    model = MealPlan
    template_name = "meal_plans/list.html"

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)


class MealPlansDetailView(DetailView):
    model = MealPlan
    template_name = "meal_plans/detail.html"


class MealPlansCreateView(LoginRequiredMixin, CreateView):
    model = MealPlan
    template_name = "meal_plans/create.html"
    fields = ["name", "date", "recipes"]

    def form_valid(self, form):
        plan = form.save(commit=False)
        plan.owner = self.request.user
        plan.save()
        form.save_m2m()
        return redirect("meal_plans_detail", pk=plan.id)


class MealPlansUpdateView(LoginRequiredMixin, UpdateView):
    model = MealPlan
    template_name = "meal_plans/edit.html"
    fields = ["name", "date", "recipes"]
    success_url = reverse_lazy("recipes_list")


class MealPlansDeleteView(LoginRequiredMixin, DeleteView):
    model = MealPlan
    template_name = "meal_plans/delete.html"
    success_url = reverse_lazy("recipes_list")

meal_plans/templates/meal_plans/create.html
{% extends 'base.html' %}

{% block content %}
 <main class="recipe-form">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="control">
        <button class="button">Create</button>
  </main>
  {% endblock content %}

meal_plans/templates/meal_plans/delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <main>
    <div class="delete-form">
      <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete {{ recipe }}?</p>
        {{ form.as_p }}
        <div>
          <button class="button">Delete</button>
        </div>
      </form>
    </div>
  </main>
  {% endblock content %}

meal_plans/templates/meal_plans/detail.html
{% extends 'base.html' %}

{% block content %}
  <main class="recipe-grid">
    <div>
        <a href="{% url 'meal_plans_edit' mealplan.pk %}">Edit</a>
        <a href="{% url 'meal_plans_delete' mealplan.pk %}">Delete</a>
    </div>
    <h1>{{ mealplan.name }}</h1>
    <h2>by: {{ mealplan.owner }}</h2>
    <p>
      date: {{ mealplan.date }}
    </p>
    {% for recipe in mealplan.recipes.all %}
    <a href="{% url 'recipe_detail' recipe.pk %}">{{ recipe.name }}</a>
    {% endfor %}

  </main>
  {% endblock content %}

meal_plans/templates/meal_plans/edit.html
{% extends 'base.html' %}

{% block content %}
  <main class="recipe-form">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="control">
        <button class="button">Update</button>
      </div>
    </form>
  </main>
{% endblock content %}

meal_plans/templates/meal_plans/list.html
{% extends 'base.html' %}

{% block pagination %}
    <div class="pagination">
      <span class="step-links">
        {% if page_obj.has_previous %}
          <a href="?page=1">&laquo; first</a>
          <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}">next</a>
          <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
      </span>
    </div>
{% endblock pagination %}

{% block content %}
  <main class="recipe-grid">
    <div>
        <a href="{% url 'meal_plans_create'%}">Create</a>
    </div>
    {% if user.is_authenticated %}
      {% for meal_plan in mealplan_list %}
        <div class="recipe-card">
          <h2 class="recipe-card-title">
            <a href="{% url 'meal_plans_detail' meal_plan.pk %}">{{ meal_plan.name }}</a>
          </h2>
          <p class="recipe-card-date">{{ meal_plan.date }}</p>
        </div>
      {% endfor %}
    {% endif %}
  </main>
  {% endblock content %}